### ISSUE TITLE
v5.0 reload bug

### ISSUE THREAD

**Issue by brjuseg** [galaipa/SuperBuildBattle#10]
1. red messages in the console after doing /bb reload
2. when you do /bb reload
3. spigot 1.8.6 SBB 5.0
4. [00:27:42] [Server thread/WARN]: Unexpected exception while parsing console command "bb reload"
org.bukkit.command.CommandException: Unhandled exception executing command 'bb' in plugin SuperBuildBattle v5.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Spigot.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:646) ~[Spigot.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:632) [Spigot.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:404) [Spigot.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:368) [Spigot.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [Spigot.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [Spigot.jar:git-Spigot-044d928-e8c6403]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_8_R3.command.ColouredConsoleSender cannot be cast to org.bukkit.entity.Player
	at io.github.galaipa.bb.SuperBuildBattle.onCommand(SuperBuildBattle.java:135) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Spigot.jar:git-Spigot-044d928-e8c6403]
	... 8 more

**Comment by galaipa** [comment]
BB reload command dosn't exist xD

**Comment by brjuseg** [comment]
well, i tried it and it caused a lot of erros in console xD
