### ISSUE TITLE
plugin dosen´t load

### ISSUE THREAD

**Issue by Max1021** [galaipa/SuperBuildBattle#14]
In the console the plugin doesn right load 

[23:40:10 ERROR]: Could not load 'plugins\Buildbattle.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/mi
necraft/server/v1_8_R3/Packet
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.j
ava:135) ~[Spigot.jar:git-Spigot-2f787bd-501372f]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.
java:329) ~[Spigot.jar:git-Spigot-2f787bd-501372f]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager
.java:251) [Spigot.jar:git-Spigot-2f787bd-501372f]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugins(CraftServer.ja
va:291) [Spigot.jar:git-Spigot-2f787bd-501372f]
        at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.jav
a:199) [Spigot.jar:git-Spigot-2f787bd-501372f]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java
:522) [Spigot.jar:git-Spigot-2f787bd-501372f]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R3/Packet
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_40]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_40]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.jav
a:64) ~[Spigot.jar:git-Spigot-2f787bd-501372f]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.j
ava:131) ~[Spigot.jar:git-Spigot-2f787bd-501372f]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.Packet

        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:91) ~[Spigot.jar:git-Spigot-2f787bd-501372f]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:86) ~[Spigot.jar:git-Spigot-2f787bd-501372f]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_40]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_40]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.jav
a:64) ~[Spigot.jar:git-Spigot-2f787bd-501372f]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.j
ava:131) ~[Spigot.jar:git-Spigot-2f787bd-501372f]
        ... 6 more

**Comment by galaipa** [comment]
What version of spigot are you using?

**Comment by galaipa** [comment]
Closed! You are not using a right version of Spigot. Use latest
